# Generated by Django 4.1.1 on 2022-09-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='ulr_slug',
            new_name='url_slug',
        ),
    ]
