# Generated by Django 4.1.1 on 2022-09-26 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0003_merchantuser_is_added_by_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='desciption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='subcategories',
            old_name='desciption',
            new_name='description',
        ),
    ]
